name: Deploy

on: [workflow_dispatch]

env:
  CLOUDFLARE_API_TOKEN: ${secret.CLOUDFLARE_API_TOKEN}
  CLOUDFLARE_ACCOUNT_ID: ${secret.CLOUDFLARE_ACCOUNT_ID}

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Cloudflare deploy
        run: wrangler pages --project-name davidontop dist
